clear all
close all
txt = fileread('posters_programme.html');

% Find the start of the line "const favs=new"

% Extract everything between <script> and "const favs=new"
tok = regexp(txt, '<script>\s*(.*?)\s*(?=const favs=new)', ...
    'tokens', 'once');
txt = tok{1};
% Remove JavaScript wrapper
txt = erase(txt, "const posters=");
txt = erase(txt, ";");

objects = regexp(txt, '\{(.*?)\}', 'tokens');

posters = struct([]);

for i = 1:length(objects)

    obj = objects{i}{1};

    % Extract fields
    posters(i).Day = getField(obj, 'Day');
    posters(i).Time = getField(obj, 'Time');
    posters(i).Topic = getField(obj, 'Topic');
    
    posters(i).Title = getField(obj, 'Title');
    posters(i).Speaker = getField(obj, 'Author');
    posters(i).CoAuthors = getField(obj, 'CoAuthors');
    posters(i).Abstract = getField(obj, 'Abstract');

    % Numeric field
    posters(i).SubmissionID = str2double(getField(obj, 'SubmissionID'));

end
% Create a nice HTML booklet from talk/poster structure
% Input:
% posters = array of structures with fields:
% Day, Time, Topic, Title, Authors, Affiliations, Abstract



% ---------------- USER DATA ----------------
% posters should already exist in workspace
% Example:
% load('talks.mat')

outputFile = 'TalkBooklet.html';
delete(outputFile)
% ---------------- HTML HEADER ----------------

fid = fopen(outputFile,'w','n','UTF-8');

fprintf(fid,[...
'<!DOCTYPE html>\n'...
'<html>\n'...
'<head>\n'...
'<meta charset="UTF-8">\n'...
'<title>Conference Talks Booklet</title>\n'...
'<style>\n'...
'@page { size: A4; margin: 18mm; }\n'...
'body {\n'...
'    font-family: "Helvetica Neue", Arial, sans-serif;\n'...
'    color: #222;\n'...
'    line-height: 1.45;\n'...
'    font-size: 11pt;\n'...
'}\n'...
'.cover {\n'...
'    height: 90vh;\n'...
'    display:flex;\n'...
'    flex-direction:column;\n'...
'    justify-content:center;\n'...
'    align-items:center;\n'...
'    text-align:center;\n'...
'}\n'...
'.cover h1 {\n'...
'    font-size: 36pt;\n'...
'    color:#1b4f72;\n'...
'}\n'...
'.cover h2 {\n'...
'    font-weight:normal;\n'...
'}\n'...
'.talk {\n'...
'    page-break-after: always;\n'...
'}\n'...
'.header {\n'...
'    border-bottom: 3px solid #1b4f72;\n'...
'    padding-bottom:8px;\n'...
'    margin-bottom:20px;\n'...
'}\n'...
'.day {\n'...
'    color:#1b4f72;\n'...
'    font-size:14pt;\n'...
'    font-weight:bold;\n'...
'}\n'...
'.time {\n'...
'    float:right;\n'...
'    font-weight:bold;\n'...
'}\n'...
'.topic {\n'...
'    font-size:13pt;\n'...
'    color:#555;\n'...
'}\n'...
'.title {\n'...
'    font-size:18pt;\n'...
'    font-weight:bold;\n'...
'    margin:15px 0;\n'...
'}\n'...
'.authors {\n'...
'    font-size:12pt;\n'...
'}\n'...
'.aff {\n'...
'    font-size:10pt;\n'...
'    color:#555;\n'...
'    margin-top:10px;\n'...
'}\n'...
'.abstract {\n'...
'    margin-top:20px;\n'...
'    text-align:justify;\n'...
'}\n'...
'.abstract h3 {\n'...
'    color:#1b4f72;\n'...
'}\n'...
'.footer {\n'...
'    margin-top:30px;\n'...
'    font-size:9pt;\n'...
'    color:#888;\n'...
'}\n'...
'</style>\n'...
'</head>\n'...
'<body>\n']);

% ---------------- COVER PAGE ----------------

fprintf(fid,[...
'<div class="cover">\n'...
'<h1>Conference Talks Booklet</h1>\n'...
'<h2>Programme and Abstracts</h2>\n'...
'<p>Generated automatically</p>\n'...
'</div>\n']);

% ---------------- TALKS ----------------

for k = 1:numel(posters)

    t = posters(k);

    fprintf(fid,'<div class="talk">\n');

    % Header
    fprintf(fid,...
    ['<div class="header">' ...
     '<span class="day">%s</span>' ...
     '<span class="time">%s</span><br>' ...
     '<span class="topic">%s</span>' ...
     '</div>\n'], ...
     escapeHTML(t.Day), ...
     escapeHTML(t.Time), ...
     escapeHTML(t.Topic));

    % Title
    fprintf(fid,...
        '<div class="title">%s</div>\n',...
        escapeHTML(t.Title));


    % Authors

    fprintf(fid,'<div class="authors">');

    if isfield(t,'Authors') && ~isempty(t.Authors)

        for a = 1:length(t.Authors)

            if a > 1
                fprintf(fid,', ');
            end

            fprintf(fid,'%s',...
                escapeHTML(t.Authors(a).name));

        end

    elseif isfield(t,'Author')

        fprintf(fid,'%s',escapeHTML(t.Author));

        if isfield(t,'CoAuthors')
            fprintf(fid,', %s',escapeHTML(t.CoAuthors));
        end
    end

    fprintf(fid,'</div>\n');


    % Affiliations

    if isfield(t,'Affiliations') && ~isempty(t.Affiliations)

        fprintf(fid,'<div class="aff">');

        for a = 1:length(t.Affiliations)

            fprintf(fid,'<sup>%d</sup> %s<br>',...
                a,...
                escapeHTML(t.Affiliations{a}));

        end

        fprintf(fid,'</div>\n');

    end


    % Abstract

    fprintf(fid,...
        '<div class="abstract"><h3>Abstract</h3>%s</div>\n',...
        formatAbstract(t.Abstract));


    fprintf(fid,...
        '<div class="footer">Talk %d</div>\n',...
        k);

    fprintf(fid,'</div>\n');

end


% ---------------- CLOSE HTML ----------------

fprintf(fid,'</body>\n</html>');

fclose(fid);

fprintf('\nCreated: %s\n',outputFile);




